name: open_nizvpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^0.4.3

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/vpn/"